### ISSUE TITLE
CL_INVALID_VALUE When Initializing

### ISSUE THREAD

**Issue by sk1tt1sh** [fireice-uk/xmr-stak-amd#1]
Receiving "Error CL_INVALID_VALUE when calling clCreateProgramWithSource on the contents of cryptonight.cl" 
https://github.com/fireice-uk/xmr-stak-amd/blob/master/amd_gpu/gpu.c#L292

I am not 100% sure what's going on. I tried to compile with a couple tweaks to the gpu.c/h files but most of what I tried was already done or defined in open_cl includes.

This is a 6x gpu system with r9 380s - It works great with wolf's xmr miner. (Compiled on same system as your stak miner.)

If you could perhaps point me in the right direction I will find the fix but this stuff is still a bit beyond me :(

**Comment by fireice-uk** [comment]
Firstly double check that clCreateProgramWithSource has the correct args. If you can sort me out a user ssh account, I will have a look myself.

**Comment by sk1tt1sh** [comment]
Dude! I apologize, I completely spaced this out. My pool had some...difficulties, ended up having to focus on resolving those. Sorry. 

So I tried adding some debug logging:

`[2017-02-14 18:04:20] : Compiling code and initializing GPUs. This will take a while...
Adding ctx[0].deviceIdx: 0, to TempDeviceList at 0Adding ctx[1].deviceIdx: 1, to TempDeviceList at 1Adding ctx[2].deviceIdx: 2, to TempDeviceList at 2
[2017-02-14` 18:04:20] : Creating opencl_ctx with args: NULL, num_gpus:3
[2017-02-14 18:04:20] : Device 0 work size 8 / 256.
[2017-02-14 18:04:21] : Error CL_INVALID_VALUE when calling clCreateProgramWithSource on the contents of cryptonight.cl`

I'll keep adding some debug details. I have a 6 gpu rig but tried with 3x config to see if it was a bad riser or something like that. They are sapphire r9 380.

**Comment by fireice-uk** [comment]
Can you post the clinfo output?

**Comment by sk1tt1sh** [comment]
Thanks.
[clinfo.txt](https://github.com/fireice-uk/xmr-stak-amd/files/777394/clinfo.txt)

**Comment by sk1tt1sh** [comment]
I thought I would be creative and try changing the cryptonight.cl file to wolf's and see if it'd run. Unsurprisingly the same results.
According to http://manpages.org/clcreateprogramwithsource/3 - the invalid value is coming from the source strings.
"CL_INVALID_VALUE if count is zero or if strings or any entry in strings is NULL."
I'm trying to figure it out. I'm just puzzled because I've seen this work elsewhere.

Thanks.

**Comment by fireice-uk** [comment]
Slightly too busy to give the amd miner as much love as it needs =). Did you try the HEAD version? I added an explicit error there if there are any problems with the GPU source files.

**Comment by sk1tt1sh** [comment]
Word I understand that. I'll give it a go.

**Comment by sk1tt1sh** [comment]
That helped me...lol.
Issue is I was starting it in the bin folder after compiling it and the path to the cl files is relative to the root of the project. moved config.txt up one level and called it via bin/xmr-stak-amd fixed it. *sheepishgrin*
