### ISSUE TITLE
New stak release coming back as a trojan

### ISSUE THREAD

**Issue by Thomasmcdaniel9** [fireice-uk/xmr-stak-amd#100]
![image](https://user-images.githubusercontent.com/19629847/30360303-5f93d5ec-9805-11e7-8e0d-537497ba43e9.png)

**Comment by aegroto** [comment]
Some malwares download miners from github to install them on infected PCs to steal their computational power and mine in background. If you don't feel safe you can still build on your own, it shouldn't be so difficult even on Windows.

**Comment by Thomasmcdaniel9** [comment]
all other stak miners i have downloaded did not have virus only amd

**Comment by aaronsace** [comment]
@Thomasmcdaniel9 It's not actually a virus. The problem is your virus checker not fireice-uk. What are do expect to happen by reporting it?

**Comment by Thomasmcdaniel9** [comment]
I use stak miner on nvidia and gpu but this on is the only one setting off the antivirus. Was just curios as why

**Comment by aaronsace** [comment]
@Thomasmcdaniel9 Feel free to PM me on bitcointalk. 

If it's an issue related to MultiPoolMiner then post it here: https://github.com/aaronsace/MultiPoolMiner/issues
