### ISSUE TITLE
JSON config parse error(offset 2180): Invalid escape character in string.

### ISSUE THREAD

**Issue by yoy123** [fireice-uk/xmr-stak-amd#108]
Hi, I managed to compile the dev version on OS X 10.12.6 with no errors but when attempting to run ./xmr-stak-amd I receive the following error:

JSON config parse error(offset 2180): Invalid escape character in string.

Config file is attached. 
[config.txt](https://github.com/fireice-uk/xmr-stak-amd/files/1308954/config.txt)

**Comment by yoy123** [comment]
Model Name:	Mac Pro
Model Identifier:  MacPro5,1
Processor Name:  6-Core Intel Xeon
Chipset Model:	AMD Radeon HD 7xxx
  Type:	GPU
  Bus:	PCIe
  Slot:	Slot-1
  PCIe Lane Width:	x16
  VRAM (Total):	3072 MB
  Vendor:	ATI (0x1002)
  Device ID:	0x6798
  Revision ID:	0x0000
  Metal:	Supported

**Comment by psychocrypt** [comment]
Please start with a new config.txt file. You changed somewhere anything
which breaks the syntax of the janson file. I looked over it but can't see
the mistake. Starting with a new file will be the fastest way.

Am 17.09.2017 10:57 schrieb "yoy123" <notifications@github.com>:

**Comment by yoy123** [comment]
Hi, thanks for your reply. I tried starting with a fresh config file and it parsed the same error

**Comment by yoy123** [comment]
Should I start completely fresh, recompiling the whole application from dev source?

**Comment by yoy123** [comment]
I recompiled and now just getting

 Selected OpenCL device index 1 doesn't exist.
