### ISSUE TITLE
skip a GPU

### ISSUE THREAD

**Issue by scottwils** [fireice-uk/xmr-stak-amd#111]
how do you configure the config.txt to skip a GPU when you have a dual GPU setup?

**Comment by psychocrypt** [comment]
index is the index for the gpu. Begin with 1 whixh menas the sexond gpu.

Am 18.09.2017 7:51 Nachm. schrieb "scottwils" <notifications@github.com>:

**Comment by scottwils** [comment]
easy enough thanks
