### ISSUE TITLE
AMD VEGA on Arch Linux

### ISSUE THREAD

**Issue by frankcoderL** [fireice-uk/xmr-stak-amd#132]
Is there someone who knows how to setup a VEGA (64) card to use `xmr-stak-amd` on Arch Linux?
Or are the drivers not yet available on Arch Linux?

I installed the [mesa-git] repository packages
https://wiki.archlinux.org/index.php/Unofficial_user_repositories#mesa-git
http://pkgbuild.com/~lcarlier/mesa-git/sources/

The vega card is detected successfully:
```
$ lspci | grep VGA
06:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega [Radeon RX Vega] (rev c1)
```
But `clinfo `  doesn't show the vega card, and so `xmr-stak-amd` doesn't work.

**Comment by psychocrypt** [comment]
I think the vega support is currently broken in linux, we get many issues
that clinfo is not running and found no device.
Please open an issue in the amd forum. Maybe you need to switch to the
latest driver or you need to use the latest kernel.

**Comment by lhl** [comment]
@frankcoderL Vega requires ROCm/ROCK kernel drivers for OpenCL support. This might help: https://github.com/RadeonOpenCompute/ROCm/issues/117 (I could compile the 1.6.x branchkernel but it'd boot up to  a black screen for me...)

**Comment by frankcoderL** [comment]
old issue
