### ISSUE TITLE
how to overclock with xmr-stak-amd just like ClaymoreCryptoNote

### ISSUE THREAD

**Issue by zjhxmjl** [fireice-uk/xmr-stak-amd#144]
Hi,guys!
   is there any ways to overclock with xmr-stak-amd just like ClaymoreCryptoNote?thx.

**Comment by radman07** [comment]
I'd also like to see some documentation on how to change settings such as mem  and core clock, intensity, voltage, etc......

**Comment by psychocrypt** [comment]
Currently xmr-stack is not overclocking your device. You need to do it via
extern tools.
This will be a feature in the mid future.

**Comment by radman07** [comment]
OK…thanks for the headsup…any chance porting this to ethOS?  Right now I believe its only available for windows10?

One suggestion: Can you add the ability to see gpu temperatures and fan speeds?

**Comment by zjhxmjl** [comment]
ok,thx

**Comment by psychocrypt** [comment]
To see fan speed and gpu temperature you should you extern monitoring
software like ganglia.

**Comment by zjhxmjl** [comment]
is there any good tools for OC on linux?

2017-10-15 14:50 GMT+08:00 psychocrypt <notifications@github.com>:

**Comment by PandaSlash** [comment]
just use the command "sensors".  Should give you fan speed and temperature of PCI and CPU
