### ISSUE TITLE
Duplicate Shares - Issue or ignorable?

### ISSUE THREAD

**Issue by tzhbami7** [fireice-uk/xmr-stak-amd#153]
Hi there,

First of all - Thanks for this great Miner :)
I'm trying to figure out why my error count is starting to increase on supportxmr. I always had some errors on my miners but they started to increase rapidly after I put some more miners on my network.

My setup:
3x 6 AMD RX 580 8GB (Bios Mod Uber Mix Timing)
about 8 CPU Miners (Intel and AMD)

I'm getting at least 3-6 Duplicate Shares per Miner / Day (Only GPU Miners)
Should I be worried or is that Duplicate Issue Error ignorable?

Log Example AMD Rig:

RESULT REPORT
Difficulty       : 148563
Good results     : 2956 / 2959 (99.9 %)
Avg result time  : 29.1 sec
Pool-side hashes : 426741988

Top 10 best results found:
|  0 |        180739802 |  1 |        124217923 |
|  2 |         93503411 |  3 |         79565787 |
|  4 |         58181008 |  5 |         52819525 |
|  6 |         37047959 |  7 |         30983888 |
|  8 |         30172919 |  9 |         27994477 |

Error details:
| Count | Error text                       | Last seen           |
|     3 | Duplicate share                  | 2017-10-23 06:16:30 |

Related Issues?

https://github.com/fireice-uk/xmr-stak-cpu/issues/246
https://github.com/fireice-uk/xmr-stak-cpu/issues/215

Thank you in advance!

Cheers
Michael

**Comment by psychocrypt** [comment]
In your case I would ignore it because 99.9% of the shares are fine.

**Comment by tzhbami7** [comment]
I'm doing an error counter reset now to see how many duplicate shares I get tomorrow at the same time.

**Comment by fireice-uk** [comment]
Are you connecting to the pool directly?

**Comment by tzhbami7** [comment]
Yes - my gpu rigs are connected directly to the pool. I'm getting some duplicate shares on my xmr node proxy but much less in comparison to my gpu miners. 1-2 per 14 days. 
12 new duplicate shares across my gpu miners (24h timerange)

Current stats:
2,162,827 valid shares
463 invalid shares

About 90% are duplicate shares. Maybe a bit more or less.
I've started tracking it automatically only a week ago.. 
I've checked it before by hand, pressing "c" on my miners :)

**Comment by psychocrypt** [comment]
You wrote something from a xmr node proxy. Do you connect the miner
directly to the pool or connect first to the node proxy and than to the
pool?

**Comment by tzhbami7** [comment]
Xmr node proxy is doing fine. I get 1-2 duplicate shares over 14 days. My amd rigs are connected directly to de02.supportxmr.xom:7777

**Comment by xmrig** [comment]
It nodejs-pool related issue, sometimes duplicated jobs received and it cause duplicated shares.
Also it happen with dwarfpool too.

**Comment by tzhbami7** [comment]
thx for the info :) well then.. I will keep an eye on it but closing the issue.
