### ISSUE TITLE
Intel HD OpenCL Mining

### ISSUE THREAD

**Issue by SamambaMan** [fireice-uk/xmr-stak-amd#157]
Is there the possibility of running the AMD opencl miner on Intel HD video cards?

Thanks in advance!

**Comment by psychocrypt** [comment]
Yes there is a PR where I added the support and a guide how to use it #56.
But save your time the gpu is slow and avoid cpu mining which is more
efficient.

**Comment by SamambaMan** [comment]
Oh, that's great.

Performance is not expected, only educational purposes, but thanks a lot anyway!
I'll check that as soon I get home from work.

**Comment by mimewear** [comment]
I just installed the most recent version (I guess the “unified” version), but after reading through several of these recent threads I’m still confused as to how I might get my intel hd card to work. I am getting the Nvidia warnings on starting which is fine, but I’m also getting a warning about AMD OpenCl. My card does indicate that it support OpenCl (got the most recent Intel OpenCl SDK to be sure), but I’m obviously missing something. I’m currently running this on a spare Windows 10 machine, though I may consider putting Linux on if it’s worth it. Thanks
