### ISSUE TITLE
No fallback/fail-over pools

### ISSUE THREAD

**Issue by prettycode** [fireice-uk/xmr-stak-amd#163]
xmr-stak-amd is awesome I am very grateful for the work the developers have put into this. Thank you!

One feature which would make it even better is being able to specify a fallback or fail-over pool if the main pool goes down.

In other words, if I'm mining on a small pool that's experiencing growing pains, and there's an outage of some sort, I'd love it if the miner could connect to a different pool when the main connection fails.

I think some other miners (e.g. Claymore) do this?

**Comment by psychocrypt** [comment]
Is part of the next release.

**Comment by prettycode** [comment]
Fantastic!
