### ISSUE TITLE
Error CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs

### ISSUE THREAD

**Issue by carlcarlsson123** [fireice-uk/xmr-stak-amd#171]
Hello everyone,

i hope to find some help here as im an absolute "noob".

Ubuntu 16.04 on Virtualbox VM. Installed amdgpu-pro-16.40 as the 17.40 file from AMD site is broken and i couldnt find another mirror yet. Everything seems fine when using "dpkg -l amdgpu-pro".
VT-x/AMD-V is active in the VM-config and its also activated in UEFI.

Graphics card is Radeon R9 390.

./start.sh brings the following error:

Compiling code and initializing GPUs. This will take a while...
Error CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for number of devices

```
- config.txt
"gpu_thread_num" : 1
"platform_index" : 0
one GPU thread configured with intensity 500, worksize 8, "affine to cpu" : false
```
```
- start.sh
export GPU_FORCE_64BIT_PTR=0
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100

/home/.../bin/xmr-stak-amd /home/.../bin/config.txt
```
... thx in advance

**Comment by ITwrx** [comment]
you may want to use clinfo to make sure opencl "sees" your card. if it doesn't show the r9390 then xmr-stak-amd can't use it. also, if you have a cpu that has an integrated gpu, you'll want to verify the platform # that opencl has for it and/or your r9 390 as you could have the wrong platform # specified in xmr-stak-amd's config.txt and it will never see your card that way.

**Comment by carlcarlsson123** [comment]
thx for the answer. i think you are right, my i5-4460 cpu is the only thing that shows up when i use clinfo...
how could i solve this? :(

**Comment by ITwrx** [comment]
it's been years since i used virtualbox but maybe it has to do with the card and virtualbox interaction? maybe opencl can't use it because it's not fully available to the guest OS?

**Comment by psychocrypt** [comment]
In the most cases VMs has no native GPU support. Please run the miner on a native system.

We released a new version of the miner: https://github.com/fireice-uk/xmr-stak
Please check if the issue still exists with the new version. 
If the problem is not fixed so far please open a new issue in [the issue section of the new reposetory](https://github.com/fireice-uk/xmr-stak/issues)
