### ISSUE TITLE
How to setup two thread in one gpu

### ISSUE THREAD

**Issue by ubbe1** [fireice-uk/xmr-stak-amd#185]
Just started mining XMR and cant understand how to do it . I have one vega 64 lc.
Recommended settings in config?

Best regards Ubbe

**Comment by psychocrypt** [comment]
please use the latest release and follow the documentation.

docu: https://github.com/fireice-uk/xmr-stak
release: https://github.com/fireice-uk/xmr-stak/releases

**Comment by ubbe1** [comment]
I do have read those links a cupple of hours but I don`t understand it.

this is start up text fom miner:
[2017-12-02 17:00:56] : Start mining: MONERO
WARNING: NVIDIA Insufficient driver!
[2017-12-02 17:00:56] : WARNING: backend NVIDIA disabled.
[2017-12-02 17:00:56] : Compiling code and initializing GPUs. This will take a while...
[2017-12-02 17:00:56] : Device 0 work size 8 / 32.
[2017-12-02 17:01:00] : Starting AMD GPU thread 0, no affinity.
[2017-12-02 17:01:00] : Starting single thread, affinity: 0.
[2017-12-02 17:01:00] : hwloc: memory pinned
[2017-12-02 17:01:00] : Starting single thread, affinity: 1.
[2017-12-02 17:01:00] : hwloc: memory pinned
[2017-12-02 17:01:00] : Starting single thread, affinity: 2.
[2017-12-02 17:01:00] : hwloc: memory pinned
[2017-12-02 17:01:00] : Fast-connecting to xmr.mixpools.org:8080 pool ...
[2017-12-02 17:01:00] : Pool xmr.mixpools.org:8080 connected. Logging in...
[2017-12-02 17:01:01] : Difficulty changed. Now: 20000.
[2017-12-02 17:01:01] : Pool logged in.
[2017-12-02 17:01:02] : Result accepted by the pool.
[2017-12-02 17:01:10] : Difficulty changed. Now: 40000.
[2017-12-02 17:01:10] : New block detected.
[2017-12-02 17:01:51] : Result accepted by the pool.
[2017-12-02 17:02:10] : Difficulty changed. Now: 80000.
[2017-12-02 17:02:10] : New block detected.

Is there two treads in one gpu?

Is this AMD.txt ok? One vega64 lc and one intel i5 igpu for the monitor.
"gpu_threads_conf" : [ // gpu: gfx901 memory:3920  // compute units: 64  { "index" : 0, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false, 
  },
  { "index" : 1, "intensity" : 1800, "worksize" : 8, "affine_to_cpu" : false, }, ],

"platform_index" : 1,

Best regards Ubbe.

**Comment by alextrezvy** [comment]
I have the same question. There is no obvious way to set up 2 threads.

**Comment by ubbe1** [comment]
Hi.
Yes you can do it. Just follow the guide.. http://vega.miningguides.com/

**Comment by Marcus-Vittek-Haakan** [comment]
I checked the links but that' doesn't precisely tell me how to enable both threads on a R9 270x. Claymore did this , I'd like to do it on xmr-stak.

**Comment by nodakhillbilli** [comment]
Taken straight from vegaminingguides:
"gpu_threads_conf" : [ 
    { "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true, "mem_chunk" : 2, "comp_mode" : true },
    { "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, 

Index 0 is one card, notice the two thread listed underneath each for 1932.  You will have to alter the intensity and worksize for your particular card though

**Comment by Marcus-Vittek-Haakan** [comment]
Alright, but I'm using an old R9 270x. I have to stick with
xmr-stak or xmrig.... is this the config? lemme give it a try.

**Comment by CCBancho** [comment]
Hi, I have a same problem.
My machine now consists of 13 GPUs; 5 GTXs , 3 of R9 270(X), 2 of R9 380, RX560, RX580 and HD7770.

A Few AMDs successfully has worked with double threads on each GPU but 5 or 6 in 8 AMDs gives a try to double threads my computer is going dump.
Then I got the err messages of cuba error!? I don't know why.
I guess AMD settings doesn't work well but the error shows you have wrong cuba settings.

**Comment by psychocrypt** [comment]
you must post the error message and the log.

**Comment by CCBancho** [comment]
Sorry for the delay of my response,
I got a successful mining with all 8 AMDs double thread setting in the end.
R9 380 intensities changed more moderate and it worked well.

As of the error message and the log, I can hardly catch well because the err shows and the miner shot down directly and even win10 freezes sometimes and got rebooted.

I took a picture of one of the err message following at the once

[cuba] Error gpu 0: <C:/xmr-stak/xmrstak/backend/nvidia/ncc_code/cuba\/extra.cu>:309

This time I got an error of gpu 0 but I guess gpu2 error like this is a familiar to me
and I got the number 309 this time but I've seen the defferent number such as 240? or something.

I don't know why the error shows you have wrong cuba settings although AMD settings doesn't work.

**Comment by CCBancho** [comment]
<work-well setting>
"gpu_threads_conf" : [
  // gpu: Pitcairn memory:1395
  // compute units: 20
  { "index" : 0,
    "intensity" : 360, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 0,
    "intensity" : 360, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Capeverde memory:1395
  // compute units: 10
  { "index" : 1,
    "intensity" : 330, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 1,
    "intensity" : 330, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Baffin memory:3136
  // compute units: 16
  { "index" : 2,
    "intensity" : 448, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 2,
    "intensity" : 464, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 3,
    "intensity" : 468, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 3,
    "intensity" : 468, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Tonga memory:1395
  // compute units: 28
  { "index" : 4,
    "intensity" : 392, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 4,
    "intensity" : 392, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Tonga memory:1395
  // compute units: 28
  { "index" : 5,
    "intensity" : 392, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 5,
    "intensity" : 392, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Pitcairn memory:1395
  // compute units: 20
  { "index" : 6,
    "intensity" : 360, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 6,
    "intensity" : 360, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Pitcairn memory:1395
  // compute units: 20
  { "index" : 7,
    "intensity" : 360, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 7,
    "intensity" : 360, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },

],

<troublesome setting>
"gpu_threads_conf" : [
  // gpu: Pitcairn memory:1395
  // compute units: 20
  { "index" : 0,
    "intensity" : 320, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 0,
    "intensity" : 340, "worksize" : 6,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Capeverde memory:1395
  // compute units: 10
  { "index" : 1,
    "intensity" : 640, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Baffin memory:3136
  // compute units: 16
  { "index" : 2,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 3,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Tonga memory:1395
  // compute units: 28
  { "index" : 4,
    "intensity" : 420, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 4,
    "intensity" : 420, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Tonga memory:1395
  // compute units: 28
  { "index" : 5,
    "intensity" : 420, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 5,
    "intensity" : 420, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Pitcairn memory:1395
  // compute units: 20
  { "index" : 6,
    "intensity" : 340, "worksize" : 6,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 6,
    "intensity" : 320, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Pitcairn memory:1395
  // compute units: 20
  { "index" : 7,
    "intensity" : 320, "worksize" : 7,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 7,
    "intensity" : 340, "worksize" : 6,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },

],

<GTX setting>
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 680 architecture: 30
  //      memory: 1666/2048 MiB
  //      smx: 8
  { "index" : 0,
    "threads" : 16, "blocks" : 32,
    "bfactor" : 10, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 570 architecture: 20
  //      memory: 986/1280 MiB
  //      smx: 15
  { "index" : 1,
    "threads" : 18, "blocks" : 27,
    "bfactor" : 10, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 560 Ti architecture: 20
  //      memory: 989/1280 MiB
  //      smx: 14
  { "index" : 2,
    "threads" : 18, "blocks" : 27,
    "bfactor" : 10, "bsleep" :  10,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 570 architecture: 20
  //      memory: 986/1280 MiB
  //      smx: 15
  { "index" : 3,
    "threads" : 18, "blocks" : 27,
    "bfactor" : 10, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 570 architecture: 20
  //      memory: 986/1280 MiB
  //      smx: 15
  { "index" : 4,
    "threads" : 18, "blocks" : 27,
    "bfactor" : 10, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by CCBancho** [comment]
Oops I got a wrong writing.
The first section is wok-well AMD setting, the second troublesome AMD setting and the third GTX setting.

**Comment by CCBancho** [comment]
There's still something wrong.

error message
 [cuba] Error gpu2: <C:/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuba_extra.cu>365
[cuba] Error gpu0: <C:/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuba_core.cu>446
**suggestion: Try to ncrease the value of the attribute 'bfactor' or reduce 'threads' in the NVIDIA config file.** 

There's ain't no wrong setting for GTXs. I got no change for GTXs setting but AMDs.

**Comment by Rakly3** [comment]
CCBanko, you can't format it like that.
Try this (for some reason the site isn't putting everything in one block of code. Include the text at the end too about platform_index.)

"gpu_threads_conf" : 
[
	// gpu: Pitcairn memory:1395
	// compute units: 20
		{ "index" : 0, "intensity" : 360, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
		{ "index" : 0, "intensity" : 360, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },

	// gpu: Capeverde memory:1395
	// compute units: 10
		{ "index" : 1, "intensity" : 330, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
		{ "index" : 1, "intensity" : 330, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },

	// gpu: Baffin memory:3136
	// compute units: 16
		{ "index" : 2, "intensity" : 448, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
		{ "index" : 2, "intensity" : 464, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },

	// gpu: Ellesmere memory:3920
	// compute units: 36
		{ "index" : 3, "intensity" : 468, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
		{ "index" : 3, "intensity" : 468, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },

	// gpu: Tonga memory:1395
	// compute units: 28
		{ "index" : 4, "intensity" : 392, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
		{ "index" : 4, "intensity" : 392, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
		{ "index" : 5, "intensity" : 392, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
		{ "index" : 5, "intensity" : 392, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },

	// gpu: Pitcairn memory:1395
	// compute units: 20
		{ "index" : 6, "intensity" : 360, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
		{ "index" : 6, "intensity" : 360, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
		{ "index" : 7, "intensity" : 360, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
		{ "index" : 7, "intensity" : 360, "worksize" : 7, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
],

// set platform_index to 1 if you have an Intell internal GPU that is turned on in the bios/UEFI (ONLY if you have enabled Intell & AMD in the same system.)
"platform_index" : 0,`
