### ISSUE TITLE
Error UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.

### ISSUE THREAD

**Issue by notmike-5** [fireice-uk/xmr-stak-amd#19]
When I attempt to run xmr-stak-amd (on Arch) I get the following error:

$ ./xmr-stak-amd 
[2017-04-18 18:26:24] : Compiling code and initializing GPUs. This will take a while...
[2017-04-18 18:26:24] : Error UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.

Running clinfo yields: 

$ clinfo
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
[1]    25102 abort (core dumped)  clinfo

Here is my config file: http://termbin.com/7sec

Kinda don't really know what to do from here. :/

**Comment by fireice-uk** [comment]
Arch is a fairly hard distro to get the proprietary drivers to run on, and this is the only option that will still leave some hair on your head. See this issue https://github.com/fireice-uk/xmr-stak-amd/issues/14

**Comment by psychocrypt** [comment]
could you also provide us with the output of `clinfo`

**Comment by notmike-5** [comment]
@psychocrypt output of clinfo is above

**Comment by notmike-5** [comment]
Ok, here is an update:

I found and installed this package in the AUR, https://aur.archlinux.org/packages/opencl-amd/

That seems to have done something good, because the clinfo command now works fine. @psychocrypt Here is the output of clinfo: http://termbin.com/8cdt

I've also modified my config to reflect the PlatformID given in that command. Here is my present config file: http://termbin.com/p2vw

Running .xmr-stak-amd, however, yields:
 
$ ./xmr-stak-amd 
[2017-04-19 15:53:26] : JSON config parse error(offset 828): Missing a comma or '}' after an object member.

I went through the config a couple times, but I can't figure out where the syntax(?) error is being generated. Appreciated all the help you can give.

**Comment by psychocrypt** [comment]
You need to set `"platform_index ": 0` and lower the intensity. Please try this

```
"gpu_threads_conf" : [ 
	{ "index" : 0, "intensity" : 512, "worksize" : 8, "affine_to_cpu" : false },
],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */

"platform_index" : 0,
```

**Comment by notmike-5** [comment]
$ ./xmr-stak-amd                      
[2017-04-19 16:19:38] : Compiling code and initializing GPUs. This will take a while...
[2017-04-19 16:19:38] : Couldn't locate GPU source code file at opencl/cryptonight.cl.

**Comment by psychocrypt** [comment]
You need to copy the folder `opencl` to you binary (see [here](https://github.com/fireice-uk/xmr-stak-amd/issues/20#issuecomment-295191451))

**Comment by notmike-5** [comment]
Appears working like a charm! Thanks, bruh bruh.

**Comment by psychocrypt** [comment]
--- solved ---
