### ISSUE TITLE
dual platforms (OpenCL and ROCM)

### ISSUE THREAD

**Issue by flicksterdoo** [fireice-uk/xmr-stak-amd#201]
I'm struggling to get a dual platform miner running correctly with the amd.txt setup.  My setup includes a Vega FE, RX580s and RX560s.  Everything is installed and compiled correctly, but I'm having difficulty getting any card that's on OpenCL=legacy platform to enumerate.  The amd.txt settings file has A provision for setting a single platform_identifier which is great when all of your devices are on the same platform.  In my case I end up with two ID 0s on two platforms, In other words VegaFE Platform0, ID0 and RX580 Platform1, ID0.  I can't figure out a way to get this working.  If needed I can attached a clinfo dump, but my explaination above should be clear enough.  I searched the issues and web and didn't see anything jump out with an answer. Thanks in advance for any pointers.

**Comment by psychocrypt** [comment]
start the miner twice. You can set the config file via command lie options.
Run xmr-stak --help to see all options.

**Comment by flicksterdoo** [comment]
Thanks!  It occurred to me right after I posted, but it was 4am and I'd shutdown for the night.

**Comment by flicksterdoo** [comment]
Worked great!  Thanks for the tip.
