### ISSUE TITLE
Error UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.

### ISSUE THREAD

**Issue by MrKaneF** [fireice-uk/xmr-stak-amd#27]
[2017-05-01 02:14:46] : Compiling code and initializing GPUs. This will take a while...
[2017-05-01 02:14:46] : Error UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.

I am running Debian Stretch with the amdgpu-pro drivers that are now in the debian repos. Everything compiled fine with no errors. I am not sure what the problem is.

~~EDIT: It appears the firmware is failing to load into the kernel still not sure how to fix that though.~~

EDIT2: After manually adding polaris10_mc.bin to /lib/firmware/amdgpu the firmware is now loading into the kernel, but I still get the exact same error as before after running ./xmr-stak-amd

'clinfo' prints Number of platforms 0

I have 6 RX 480s installed.

**Comment by psychocrypt** [comment]
Please run `clinfo` int the terminal and post the output plus your config.

**Comment by MrKaneF** [comment]
I am going to close the issue for now. I am going to reinstall debian stretch and if I run into any problems I'll make another issue.

**Comment by fireice-uk** [comment]
To retain your sanity I would strongly advise to use proprietary AMD drivers, I found that they are the only ones that work without issues.

**Comment by diederikdehaas** [comment]
Just wanted to let you know that I experienced the exact same error.
Card: Radeon RX 460
OS: Debian Stretch as Dom0 (Xen version 4.8.1)
Driver: `/lib/modules/4.9.0-3-amd64/kernel/drivers/gpu/drm/amd/amdgpu/amdgpu.ko` (thus the linux kernel driver module)
```
# clinfo
Number of platforms                               0
```

**Comment by psychocrypt** [comment]
@diederikdehaas Your driver is not working. If clinfo is not showing your gpu something is wrong with your driver.

**Comment by diederikdehaas** [comment]
@psychocrypt ok, thanks. I'll take it up with the Debian Maintainer(s) then.

**Comment by Divided-Pi** [comment]
@diederikdehaas did you find a solution to this? I'm having the same problem

**Comment by diederikdehaas** [comment]
No, but haven't tried much tbh.
