### ISSUE TITLE
Fan speed issue when using custom bios

### ISSUE THREAD

**Issue by Lafudoci** [fireice-uk/xmr-stak-amd#31]
Hi, I got a weird problem. At first, this miner works great on my RX470. But after I flashed [VBIOS from Λnorak](https://forum.z.cash/t/anoraks-vbios-collection-optimized-settings-for-performance-power-saving/8347) to boost the hashrate, the fan speed goes crazy full speed, makes loud noise. But the weird thing is it does not happen on starting of mining, need about 30 mins after starting instead. The hashrate keeps good without any error, just fan speed problem. And it's not caused by overheat. The temp is only 50-60c. [The GPU-Z showed the fan speed is 0%](http://imgur.com/a5gk42v). It also happened on XMR claymore miner. But there is no the same issue on ETH claymore miner by same card & bios. And this issue happened on my 3 different rig with different motherboards & different GPU brands. Could you have a look what's the problem? Thank you so much!

**Comment by fireice-uk** [comment]
The miner does not have any fan control right now so any problem is squarely with the bios.

**Comment by Lafudoci** [comment]
But I don't understand why the custom bios works well on ETH minig. The bios only has timing modified. Is that possible that XMR algorithm doesn't compatible with specific timing setting and makes AMD driver crash? It'll be so great if this issue could be solved because the bios boost the xmr hashrate a lot.

**Comment by psychocrypt** [comment]
The ETH mining algorithm is different to XMR. A XMR miner is heavily using the GPU main memory, this can be the reason why XMR miner crashing the modded bios.

All in all it looks like an error in the bios mod and can't influenced by use.
