### ISSUE TITLE
Error: Selected OpenCL device index 1 doesn't exist.

### ISSUE THREAD

**Issue by Scorpioner48** [fireice-uk/xmr-stak-amd#41]
Any clue on how to fix this? I am running the most recent version.

**Comment by fireice-uk** [comment]
Make sure you edit the cpnfig to match your gpu count and capability.

**Comment by Scorpioner48** [comment]
I do believe I am quite the idiot 😆 I was setting up the GPU miner similarly to your CPU miner. I simply switched over to the CPU miner.
