### ISSUE TITLE
Suggestions on config for multiple different GPU

### ISSUE THREAD

**Issue by jszczerb** [fireice-uk/xmr-stak-amd#43]
I've got (2) Radeon Rx460 (1gb), (1) Radeon RX470 (4gb), and (1) Radeon RX480 (8gb) in one rig

I've got the config for all (4) set at 8, 512...when I run it says 8 and 256 for all 4 cards.   Is that correct?  or is that a display bug?  

Second question... can you put different values for each card to optimize for that card?

Third question...Whats a recommend increment values?

thanks
jeff

**Comment by psychocrypt** [comment]
Please post the terminal output.

**Comment by jszczerb** [comment]
[2017-06-06 15:51:07] : Compiling code and initializing GPUs. This will take a while...
[2017-06-06 15:51:07] : Device 0 work size 8 / 256.
[2017-06-06 15:51:14] : Device 1 work size 8 / 256.
[2017-06-06 15:51:20] : Device 2 work size 8 / 256.
[2017-06-06 15:51:27] : Device 3 work size 8 / 256.
-------------------------------------------------------------------
XMR-Stak-AMD mining software, AMD Version.
AMD mining code was written by wolf9466.
Brought to you by fireice_uk under GPLv3.

Configurable dev donation level is set to 1.0 %

**Comment by psychocrypt** [comment]
`8 / 256` means that you have configured 8 and the maximum work size supported by your devices is `256`.
Btw: `256` is not usable, in your case `32` is the maximum (this has something to do how some kernel are called)

**Comment by jszczerb** [comment]
here's the snipped from the config.txt :       

"gpu_threads_conf" : [ 
	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false },
        { "index" : 1, "intensity" : 512, "worksize" : 8, "affine_to_cpu" : false },
        { "index" : 2, "intensity" : 512, "worksize" : 8, "affine_to_cpu" : false }, 
        { "index" : 3, "intensity" : 1024, "worksize" : 8, "affine_to_cpu" : false },


],

**Comment by jszczerb** [comment]
and here is real results:  

HASHRATE REPORT
| ID |   10s |   60s |   15m | ID |   10s |   60s |   15m |
|  0 | 536.0 | 536.0 |  (na) |  1 | 305.5 | 305.6 |  (na) |
|  2 | 305.9 | 305.8 |  (na) |  3 | 593.6 | 593.5 |  (na) |
-----------------------------------------------------
Totals:   1740.9 1740.8  (na) H/s
Highest:  1741.2 H/s

**Comment by psychocrypt** [comment]
Issue is solved the number `256` is the maximum supported work size of the gpu.
