### ISSUE TITLE
Fatal error: 'CL/cl.h' file not found

### ISSUE THREAD

**Issue by 350d** [fireice-uk/xmr-stak-amd#52]
Hello!
I can't compile on Mac with this error:

    In file included from /Users/username/xmr-stak-amd/amd_gpu/gpu.c:43:
    /Users/username/xmr-stak-amd/amd_gpu/gpu.h:3:10: fatal error: 'CL/cl.h' file not found
    #include <CL/cl.h>

**Comment by coruble** [comment]
@350d Just replace `CL/cl.h` by `OpenCL/cl.h`, or apply the whole #17 patch

**Comment by psychocrypt** [comment]
The fix for MAC support is currently not merged because we are still testing see #17

**Comment by psychocrypt** [comment]
The fix is now available in the dev branch.
