### ISSUE TITLE
Ubuntu 16.04.02 + AMDGPU_PRO + HD7850 = Error CL_OUT_OF_HOST_MEMORY when calling clCreateCommandQueueWithProperties.

### ISSUE THREAD

**Issue by telo01** [fireice-uk/xmr-stak-amd#53]
Hello,
thank you for your code.
compiled successfully
i tried to run, but got an error:
```
[2017-06-19 21:28:55] : Compiling code and initializing GPUs. This will take a while...
[2017-06-19 21:28:56] : Device 0 work size 8 / 256.
[2017-06-19 21:28:56] : Error CL_OUT_OF_HOST_MEMORY when calling clCreateCommandQueueWithProperties.
```
config.txt:
```
"gpu_thread_num" : 1,
"gpu_threads_conf" : [
        { "index" : 0, "intensity" : 8, "worksize" : 8, "affine_to_cpu" : false },
],
"platform_index" : 0,
```
amdgpu-pro installed.

<details>
  <summary>clinfo:</summary><pre>
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP (2348.3)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 2
  Device Name                                     Pitcairn
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 AMD-APP (2348.3)
  Driver Version                                  2348.3
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Board Name (AMD)                         AMD Radeon HD 7800 Series
  Device Topology (AMD)                           PCI-E, 01:00.0
  Max compute units                               8
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             860MHz
  Graphics IP (AMD)                               6.0
  Device Partition                                (core)
    Max number of sub-devices                     8
    Supported partition types                     none specified
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
  Wavefront width (AMD)                           64
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    32, Little-Endian
  Global memory size                              1750908928 (1.631GiB)
  Global free memory (AMD)                        <printDeviceInfo:68: get number of CL_DEVICE_GLOBAL_FREE_MEMORY_AMD : error -33>
  Global memory channels (AMD)                    8
  Global memory banks per channel (AMD)           16
  Global memory bank width (AMD)                  256 bytes
  Error Correction support                        No
  Max memory allocation                           1143533568 (1.065GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       2048 bits (256 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 bytes
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Local memory syze per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        1497770159747264570ns (Sun Jun 18 10:15:59 2017)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Thread trace supported (AMD)                  No
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event 

  Device Name                                     Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  Device Vendor                                   GenuineIntel
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 AMD-APP (2348.3)
  Driver Version                                  2348.3 (sse2,avx)
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE
  Device Board Name (AMD)                         
  Device Topology (AMD)                           (n/a)
  Max compute units                               8
  Max clock frequency                             3699MHz
  Device Partition                                (core, cl_ext_device_fission)
    Max number of sub-devices                     8
    Supported partition types                     equally, by counts, by affinity domain
    Supported affinity domains                    L3 cache, L2 cache, L1 cache, next partitionable
    Supported partition types (ext)               equally, by counts, by affinity domain
    Supported affinity domains (ext)              L3 cache, L2 cache, L1 cache, next fissionable
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             1024
  Preferred work group size multiple              1
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 4 / 4        (n/a)
    float                                                8 / 8       
    double                                               4 / 4        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              16775053312 (15.62GiB)
  Error Correction support                        No
  Max memory allocation                           4193763328 (3.906GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        32768
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             8192x8192 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                64
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     8
  Max size of kernel argument                     4096 (4KiB)
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        1497770159747264570ns (Sun Jun 18 10:15:59 2017)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 1.2
  printf() buffer size                            65536 (64KiB)
  Built-in kernels                                
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_spir cl_khr_gl_event 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [AMD]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform
</pre>
</details>

thanks in advance

**Comment by psychocrypt** [comment]
It looks like an graphic driver error, see https://stackoverflow.com/questions/39864947/opencl-cl-out-of-host-memory-on-clcreatecommandqueuewithproperties-with-minima

Please update your driver.

**Comment by telo01** [comment]
reinstall (fresh download) driver, recompile project. still no luck
```
~$ dpkg-query -l amdgpu-pro
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version        Architecture   Description
+++-==================-==============-==============-==========================================
ii  amdgpu-pro         17.10-429170   amd64          Meta package to install amdgpu Pro compone
~$ dpkg-query -l ocl-icd-opencl-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version        Architecture   Description
+++-==================-==============-==============-==========================================
ii  ocl-icd-opencl-dev 2.2.8-1        amd64          OpenCL development files

```
```
~$ modinfo amdgpu
filename:       /lib/modules/4.8.0-54-generic/updates/dkms/amdgpu.ko
version:        17.10.2
license:        GPL and additional rights
```
```
xmr-stak-amd$ ./bin/xmr-stak-amd 
[2017-06-20 00:06:55] : Compiling code and initializing GPUs. This will take a while...
[2017-06-20 00:06:57] : Device 0 work size 8 / 256.
[2017-06-20 00:06:57] : Error CL_OUT_OF_HOST_MEMORY when calling clCreateCommandQueueWithProperties.
```

**Comment by psychocrypt** [comment]
I used ubuntu 14.04 with my old amd gpu because I never get opencl in newer ubuntu versions running.
You could also try to use a older driver version.

**Comment by gsedej** [comment]
I was able to install amdgpu-pro 17.10 on 16.04.2 (kernel 4.4) and use opencl on R9 270, it should be similar family to HD7850. you have to put `exportˇ and also play a bit with settings
https://github.com/fireice-uk/xmr-stak-amd/issues/5#issuecomment-308925034

**Comment by telo01** [comment]
@psychocrypt 
thank you. under 14.04 with kernel 3.13 it works fine.
@gsedej 
yes, with this environments it doing right. thank you for participating.

btw, at 14.04 fglrx 7850 2gb ram make 300h/s, 16.04 amdgpu-pro make 275h/s

**Comment by phobicdotno** [comment]
testing

**Comment by phobicdotno** [comment]
Hello.

I have the same problem. After two days fiddling I managed to install Ubuntu 16.04 Server with GPU HD7870 on a machine I bought cheap. . Compiled xmr-stak-amd and ran mining, sometime in the night the mining crashed. And when I try starting it again i get this:

"platform_index" : 0,
```
karstein@phobic-x6:~/Downloads/xmr-stak-amd/bin$ ./startup.sh 
[2017-10-19 09:39:39] : Compiling code and initializing GPUs. This will take a while...
[2017-10-19 09:39:39] : Error CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for number of devices.
```
"platform_index" : 1,
```
karstein@phobic-x6:~/Downloads/xmr-stak-amd/bin$ ./startup.sh 
[2017-10-19 09:27:44] : Compiling code and initializing GPUs. This will take a while...
[2017-10-19 09:27:44] : Device 0 work size 8 / 256.
[2017-10-19 09:27:44] : Error CL_OUT_OF_HOST_MEMORY when calling clCreateCommandQueueWithProperties.
```
I got the same problem  above, yesterday - with intensity: 1000
Set it down to 700-800, and it worked.

But today no values work. 

[config.txt](https://github.com/fireice-uk/xmr-stak-amd/files/1397497/config.txt)
[startup.sh.txt](https://github.com/fireice-uk/xmr-stak-amd/files/1397502/startup.sh.txt)
