### ISSUE TITLE
Running on OSX error

### ISSUE THREAD

**Issue by yxd117** [fireice-uk/xmr-stak-amd#62]
Hi I need some to help to get it running on OSX.
I have built it but still I got error when I run.
I think the error is in the open.cl as_long function. However, I do not know how to solve it.
[2017-07-15 10:47:25] : Compiling code and initializing GPUs. This will take a while...
[2017-07-15 10:47:25] : Device 0 work size 8 / 512.
[2017-07-15 10:47:25] : Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.
Build log:
<program source>:16:26: warning: unknown OpenCL extension 'cl_amd_media_ops2' - ignoring
#pragma OPENCL EXTENSION cl_amd_media_ops2 : enable
                         ^
In file included from <program source>:18:
/Users/reset/Downloads/xmr-stak-amd/bin/./opencl/wolf-aes.cl:76:7: warning: no previous prototype for function 'AES_Round'
uint4 AES_Round(const __local uint *AES0, const __local uint *AES1, const __local uint *AES2, const __local uint *AES3, const uint4 X, const uint4 key)
      ^
/Users/reset/Downloads/xmr-stak-amd/bin/./opencl/wolf-aes.cl:79:14: warning: implicit declaration of function 'amd_bfe' is invalid in C99
        Y.s0 = AES0[BYTE(X.s0, 0)] ^ AES1[BYTE(X.s1, 1)] ^ AES2[BYTE(X.s2, 2)] ^ AES3[BYTE(X.s3, 3)];
             ^
/Users/reset/Downloads/xmr-stak-amd/bin/./opencl/wolf-aes.cl:74:21: note: expanded from macro 'BYTE'
#define BYTE(x, y)      (amd_bfe((x), (y) << 3U, 8U))
                    ^
In file included from <program source>:19:
/Users/reset/Downloads/xmr-stak-amd/bin/./opencl/wolf-skein.cl:31:7: warning: no previous prototype for function 'SKEIN_ROT'
ulong SKEIN_ROT(const uint2 x, const uint y)
      ^
/Users/reset/Downloads/xmr-stak-amd/bin/./opencl/wolf-skein.cl:33:29: warning: implicit declaration of function 'amd_bitalign' is invalid in C99
        if(y < 32) return(as_ulong(amd_bitalign(x, x.s10, 32 - y)));
                            ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4274:43: note: expanded from macro 'as_ulong'
#define as_ulong( _x )  __builtin_astype( _x, ulong )
                                          ^
In file included from <program source>:19:
/Users/reset/Downloads/xmr-stak-amd/bin/./opencl/wolf-skein.cl:33:20: error: invalid reinterpretation: sizes of 'ulong' (aka 'unsigned long') and 'int' must match
        if(y < 32) return(as_ulong(amd_bitalign(x, x.s10, 32 - y)));
                   ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4274:25: note: expanded from macro 'as_ulong'
#define as_ulong( _x )  __builtin_astype( _x, ulong )
                        ^
In file included from <program source>:19:
/Users/reset/Downloads/xmr-stak-amd/bin/./opencl/wolf-skein.cl:34:14: error: invalid reinterpretation: sizes of 'ulong' (aka 'unsigned long') and 'int' must match
        else return(as_ulong(amd_bitalign(x.s10, x, 32 - (y - 32))));
             ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4274:25: note: expanded from macro 'as_ulong'
#define as_ulong( _x )  __builtin_astype( _x, ulong )
                        ^
In file included from <program source>:19:
/Users/reset/Downloads/xmr-stak-amd/bin/./opencl/wolf-skein.cl:37:6: warning: no previous prototype for function 'SkeinMix8'
void SkeinMix8(ulong4 *pv0, ulong4 *pv1, const uint rc0, const uint rc1, const uint rc2, const uint rc3)
     ^
/Users/reset/Downloads/xmr-stak-amd/bin/./opencl/wolf-skein.cl:47:8: warning: no previous prototype for function 'SkeinEvenRound'
ulong8 SkeinEvenRound(ulong8 p, const ulong8 h, const ulong *t, const uint s)
       ^
/Users/reset/Downloads/xmr-stak-amd/bin/./opencl/wolf-skein.cl:68:8: warning: no previous prototype for function 'SkeinOddRound'
ulong8 SkeinOddRound(ulong8 p, const ulong8 h, const ulong *t, const uint s)
       ^
/Users/reset/Downloads/xmr-stak-amd/bin/./opencl/wolf-skein.cl:89:8: warning: no previous prototype for function 'Skein512Block'
ulong8 Skein512Block(ulong8 p, ulong8 h, ulong h8, const ulong *t)
       ^
<program source>:57:6: warning: no previous prototype for function 'keccakf1600'
void keccakf1600(ulong *s)
     ^
<program source>:117:6: warning: no previous prototype for function 'keccakf1600_1'
void keccakf1600_1(ulong *st)
     ^
<program source>:176:6: warning: no previous prototype for function 'keccakf1600_2'
void keccakf1600_2(ulong *st)
     ^
<program source>:304:6: warning: no previous prototype for function 'CNKeccak'
void CNKeccak(ulong *output, ulong *input)
     ^
<program source>:328:26: warning: unknown OpenCL extension 'cl_amd_media_ops2' - ignoring
#pragma OPENCL EXTENSION cl_amd_media_ops2 : enable
                         ^
<program source>:334:6: warning: no previous prototype for function 'AESExpandKey256'
void AESExpandKey256(uint *keybuf)
     ^

**Comment by fireice-uk** [comment]
If you are feeling brave check out the dev branch. This has been addressed there.

**Comment by yxd117** [comment]
Thanks I just built from dev and it can run now. The hashrate is ok. However, the compute errors seems too high to me. I usually get few errors when I mine with CPU. And running GPU and CPU miner concurrently  lowers my CPU hash rate quite a lot.

Here is the resutt of running using GPU.

[2017-07-16 10:23:01] : Result accepted by the pool.
RESULT REPORT
Difficulty       : 1000
Good results     : 27 / 52 (51.9 %)
Avg result time  : 9.7 sec
Pool-side hashes : 27000

Top 10 best results found:
|  0 |           148612 |  1 |             4996 |
|  2 |             3021 |  3 |             2470 |
|  4 |             2212 |  5 |             2190 |
|  6 |             2099 |  7 |             2027 |
|  8 |             1990 |  9 |             1987 |

Error details:
| Count | Error text                       | Last seen           |
|    25 | [GPU COMPUTE ERROR]              | 2017-07-16 10:22:32 |
[2017-07-16 10:23:18] : Result accepted by the pool.

**Comment by fireice-uk** [comment]
Unfortunately the errors are caused by the hardware factors (temperature, clocking and age, in that order roughly). When running a dual cpu-gpu setup, it is best to leave one core idle.

**Comment by pavel-shpilev** [comment]
Very similar results when run on 15' MacBook Pro 2016 with Radeon Pro 460. I am very confident that clocking and age aren't to blame here. My machine is only three month old, and no overclocking.
Temperature - possibly, errors start to appear after 30mins to 1hr after "cold" launch.

I should get my eGPU enclosure soon to test on a proper graphics card. I am also going to install Ubuntu to see whether errors persist, and whether it is MacOS or mobile Radeon Pro specific.

**Comment by pavel-shpilev** [comment]
Ok, I managed to try in on Windows (no luck with Linux just yet) and I can confirm that GPU errors do not happen there. I also tried it with 1080ti in akitio node, and that works fine as well. So looks like this has something to do with AMD drivers on macOS.

**Comment by chenh3** [comment]
I have the same problem, but not sure what is the dev branch. I am new here, thanks.

**Comment by chenh3** [comment]
I got it, thanks.

**Comment by yoy123** [comment]
Please close this issue if it is solved. 

@yxd117

**Comment by yxd117** [comment]
I think it's the problem on the amd card on macOS. If someone have some problems just open another issue.
