### ISSUE TITLE
Intensity and worker value

### ISSUE THREAD

**Issue by hoyanf** [fireice-uk/xmr-stak-amd#68]
Hi, is there a method to properly configure intensity and worker value based on running hardware ?

As on CPU it's based on L3 Cache size, so on GPU what should be the guide ?

**Comment by fireice-uk** [comment]
I believe that autoconfig that we have on cpu and nvidia version will come to amd eventually =)

**Comment by hoyanf** [comment]
Ok then, i'll close this. Thanks a bunch. 🥇
