### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by xmr-eric** [fireice-uk/xmr-stak-amd#7]
After editing config with the right settings, I'm getting the following error whenever I run xmr-stak-amd.exe on Win64:

Compiling code and initializing GPUs. This will take a while...
Device 0 worksize 8 / 1024
Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.
Press any key to exit

**Comment by xmr-eric** [comment]
CLInfo: https://paste.fedoraproject.org/paste/OTXP-cTKLdUUyegZBRxsQV5M1UNdIGYhyRLivL9gydE=

**Comment by fireice-uk** [comment]
Hi, what's your platform id? It needs to be 1 since platform 0 is taken up by an nvidia driver.

**Comment by xmr-eric** [comment]
That worked. Thanks
