### ISSUE TITLE
Error CL_DEVICE_NOT_FOUND on Crimson 17.7.2

### ISSUE THREAD

**Issue by atherosxd** [fireice-uk/xmr-stak-amd#70]
It was working on crimson 17.7.1, but after I  have updated to 17.7.2, it doesn't work anymore.

**Comment by psychocrypt** [comment]
Please check you driver. Could you please run `clinfo` on the terminal.

**Comment by psychocrypt** [comment]
closed, no user response (please open an new issue if you have still problems)
