### ISSUE TITLE
Can't compile as per README.md instructions (issue now fixed, readme will be updated too)

### ISSUE THREAD

**Issue by futurepr0n** [fireice-uk/xmr-stak-amd#74]
futurepr0n@futureMedia:~/xmr-stak-amd/bin$ ./xmr-stak-amd ../config.txt 
[2017-08-15 23:37:04] : Compiling code and initializing GPUs. This will take a while...
[2017-08-15 23:37:04] : Couldn't locate GPU source code file at opencl/cryptonight.cl.

I only have one gpu, AMD RX 460, here is my config:

```
/*
 * Number of GPUs that you have in your system. Each GPU will get its own CPU thread.
 */
"gpu_thread_num" : 1,

/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 */
"gpu_threads_conf" : [
        { "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false },
],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,

/*
 * TLS Settings
 * If you need real security, make sure tls_secure_algo is enabled (otherwise MITM attack can downgrade encryption
 * to trivially breakable stuff like DES and MD5), and verify the server's fingerprint through a trusted channel.
 *
 * use_tls         - This option will make us connect using Transport Layer Security.
 * tls_secure_algo - Use only secure algorithms. This will make us quit with an error if we can't negotiate a secure algo.
 * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
 */
"use_tls" : false,
"tls_secure_algo" : true,
"tls_fingerprint" : "",

/*
 * pool_address   - Pool address should be in the form "pool.supportxmr.com:3333". Only stratum pools are supported.
 * wallet_address - Your wallet, or pool login.
 * pool_password  - Can be empty in most cases or "x".
 */
"pool_address" : "pool.supportxmr.com:3333",
"wallet_address" : "46BbNCDgBXGBNKeJfyuHTidUHh9wzf2jgP17HqQbY6x9iC1zgbR2Kxti8yV5E82Qbc9wR1nNjMmQBE2izbyUFfnYSyR6emr",
"pool_password" : "",

/*
 * Network timeouts.
 * Because of the way this client is written it doesn't need to constantly talk (keep-alive) to the server to make
 * sure it is there. We detect a buggy / overloaded server by the call timeout. The default values will be ok for
 * nearly all cases. If they aren't the pool has most likely overload issues. Low call timeout values are preferable -
 * long timeouts mean that we waste hashes on potentially stale jobs. Connection report will tell you how long the
 * server usually takes to process our calls.
 *
 * call_timeout - How long should we wait for a response from the server before we assume it is dead and drop the connection.
 * retry_time   - How long should we wait before another connection attempt.
 *                Both values are in seconds.
 * giveup_limit - Limit how many times we try to reconnect to the pool. Zero means no limit. Note that stak miners
 *                don't mine while the connection is lost, so your computer's power usage goes down to idle.
 */
...
```

Everything else is stock

Any idea?

**Comment by fireice-uk** [comment]
`make install` as per the readme.md instructions

**Comment by futurepr0n** [comment]
Thanks @fireice-uk  -- Perhaps readme needs an update? I saw the following:

```
 sudo apt-get install ocl-icd-opencl-dev libmicrohttpd-dev libssl-dev cmake build-essential
    cmake .
    make
```

Now - even though I seem to be missing lOpenCL - 'make install' should clear this? I have installed the AMD App SDK and latest AMD drivers for my ubuntu 16.04 box... this -lOpenCL missing has been driving me up the wall.

Thanks for the help!

**Comment by fireice-uk** [comment]
Somehow we forgot to update the instructions in the readme.md in this version of the miner. You seem to have complied the miner ok, so nothing in those instructions will help.

Try `clinfo` - most likely it will crash / fail, meaning you have a driver problem. If not, post the output.

**Comment by futurepr0n** [comment]
used make install and then was able to run the miner after changing intensity to 500 in my config.txt. One issue is I dont seem to connect to the pool:


- RECEIVE error: socket closed
[2017-08-16 12:39:31] : Pool connection lost. Waiting 10 s before retry (attempt 4).

seems to happen repeatedly. Is this normal?

**Comment by fireice-uk** [comment]
Nope, it should be pretty fast, the problem will be with your connection or the pool's connection

**Comment by futurepr0n** [comment]
hmm.. shit... well ok, ill have a look further into then. Do you have any pool suggestions? The default one did not connect for me - and this one connects but appears to hang. When I use a CPU miner (YAM) it tells me to put crytpmonero.com:1001/xmr - I don't suppose that is required (the /xmr) in your app? or http for that matter? 

Thanks again!! Almost there....

**Comment by fireice-uk** [comment]
http://www.moneropools.com/ is a good pool list. However the default works for me - might be a problem on your side.

**Comment by futurepr0n** [comment]
interesting- well, I can say that the CPU miner on the same rig is connecting and seemingly going without an issue. The GPU one, I am kicking that off remotely using putty - but its on the same box as is connecting with no issue to cryptmonero (although it times out from time to time).

I will try another pool, but if that fails as well, could it be related to something else? The original Pool was giving me some errors recieving socket.. Maybe this is a dumb question, but would I need to run this as root?

**Comment by futurepr0n** [comment]
mine.moneropool appears to be correcting everything! Thanks again for the wicket application - going to close this issue, but would lastly like to add - is there any wallet suggestions you have or how can you speed up the synchronization on that? Ive had monero-wallet-gui open for 24 hours, and still showing  130,000 blocks remaining, been painfully slow...

**Comment by fireice-uk** [comment]
Unfortunately, no wallet sync is extremely inefficient. There is a band-aid of starting from a higher block.
