### ISSUE TITLE
Error CL_OUT_OF_RESOURCES when calling clCreateContext.

### ISSUE THREAD

**Issue by botanicaljoss** [fireice-uk/xmr-stak-amd#75]
Hello, I would greatly appreciate any assistance you can give with my issue. I have been trying to resolve it for many days.

I receive the following error when running the program since flashing the following GPU:
Error CL_OUT_OF_RESOURCES when calling clCreateContext.
Dual-X R9 270X 2G D5

The program was mining successfully before I attempted to flash the GPU, as far as I am aware the flash was successful as the GPU works when testing with modern games. The GPU is now running Bios version 015.039.000.001 and was flashed through DOS with ATIFlash successfully, following this I ran atikmdag-patcher-1.4.5 successfully.

Please find an array of logs and outputs below: 

[clinfo-output.txt](https://github.com/fireice-uk/xmr-stak-amd/files/1233037/clinfo-output.txt)
[config.txt](https://github.com/fireice-uk/xmr-stak-amd/files/1233039/config.txt)
[gpu-info.txt](https://github.com/fireice-uk/xmr-stak-amd/files/1233036/gpu-info.txt)
[xmr-stak-amd_error.txt](https://github.com/fireice-uk/xmr-stak-amd/files/1233038/xmr-stak-amd_error.txt)

**Comment by psychocrypt** [comment]
Please set the option `"platform_index"` to `2` to select the AMD driver. 

```
"platform_index" : 0,
```

**Comment by botanicaljoss** [comment]
Haha was that all it was! *headdesk*
Thank you for your assistance, your program is fantastic and your support brilliant.
