### ISSUE TITLE
Not showing hashrate

### ISSUE THREAD

**Issue by joshuaguild** [fireice-uk/xmr-stak-amd#79]
First off, thanks for the miner! It's pretty incredible (that goes for the CPU version too).

I recently hooked up 4 Vega 64s and the hashrate report seems to stop working after a few minutes. The cards continue to hash away but nothing is reported to the window or when I access it remotely. 

Happy to provide any details!

System specs:
Windows 10 64 bit
AMD 17.8.2 Driver
AsRock BTC H81
4x Vega 64 (Gigabyte, Powercolor, 2x XFX)

**Comment by joshuaguild** [comment]
Disregard, hashrate came back after a few minutes :shrug:

**Comment by fireice-uk** [comment]
This can be caused by very low difficulty settings on slow cpus, as the results are checked on the main thread.

**Comment by joshuaguild** [comment]
Ah yeah, that could be it. I only have a little baby Celeron powering the thing right now.
