### ISSUE TITLE
Problem running xmr-stak-amd as a service with systemd

### ISSUE THREAD

**Issue by tallakt** [fireice-uk/xmr-stak-amd#86]
Hi. The miner runs well from the command line. But I made a simple service file, and the miner just freezes before I get any output.

```
$ cat /etc/systemd/system/monero.service
[Unit]
Description="Monero xmr-stak-amd miner"
Wants=network-online.target
After=network-online.target

[Service]
; User=tallakt
WorkingDirectory=/home/tallakt/xmr-stak-amd
ExecStart=/bin/sh -c "/home/tallakt/xmr-stak-amd/bin/xmr-stak-amd"
Restart=always
RestartSec=15

[Install]
WantedBy=multi-user.target
```

Giving me the status:

```
$ systemctl status monero
● monero.service - "Monero xmr-stak-amd miner"
   Loaded: loaded (/etc/systemd/system/monero.service; disabled; vendor preset: enabled)
   Active: active (running) since ma. 2017-08-28 22:40:44 CEST; 9s ago
 Main PID: 26467 (sh)
   CGroup: /system.slice/monero.service
           ├─26467 /bin/sh -c /home/tallakt/xmr-stak-amd/bin/xmr-stak-amd
           └─26468 /home/tallakt/xmr-stak-amd/bin/xmr-stak-amd

aug. 28 22:40:44 miner1 systemd[1]: Started "Monero xmr-stak-amd miner".
```

(and nothing more)

A similar script ran well for an ethereum miner.

**Comment by tallakt** [comment]
Actually adding a printf as the first statement in the main() function did not produce any output when running as a service

**Comment by tallakt** [comment]
I just realized this is due to stdout buffering. Adding the following line will fix the issue:

        setbuf(stdout, NULL);

Somewhere before output starts...

**Comment by psychocrypt** [comment]
The option `flush_stdout` will sove this issue. This option is available in the new release https://github.com/fireice-uk/xmr-stak.
