### ISSUE TITLE
JSON config parse error(offset 1720): Missing a name for object member.

### ISSUE THREAD

**Issue by rebornwang** [fireice-uk/xmr-stak-amd#88]
Hi!
I'm trying to use xmr-stak-cpu-notls but receive the error:
[2017-08-30 14:36:23] : JSON config parse error(offset 1720): Missing a name for object member.
Anyone knows how to correct # this?
Thanks.
here's my config
[config1.txt](https://github.com/fireice-uk/xmr-stak-amd/files/1264122/config1.txt)

**Comment by psychocrypt** [comment]
please remove `null,`

**Comment by rebornwang** [comment]
not work
