### ISSUE TITLE
Call executable from arbitrary folder

### ISSUE THREAD

**Issue by ark02** [fireice-uk/xmr-stak-amd#96]
I would like to run xmr-stak-amd from a shell script, but cannot do so as xmr-stak-amd looks for dependencies in the directory that it was called from. 

How can I fix/workaround this?

**Comment by aaronsace** [comment]
Set the working directory first. 
In command prompt it is CD which stands for change directory.

**Comment by psychocrypt** [comment]
as @aaronsace  wrote please cd first to the folder with the binary and execute the binary directly.
